<!doctype html public "-//W3C//DTD HTML 3.2//EN">
<!--#config errmsg="There has been an error.  Please notify webmaster@functionalobjects.com" -->
<?php $current_part = "resources";
   $current_sub = "gwydion";
   $title = "Functional Objects, Inc.";
   $description = "Functional Objects -- software development tools combining ease of use with power and efficiency.";
   require "../config.php3";
?>

<?php include $top_inc ?>

<h2>Gwydion Dylan Development Cooperative</h2>

<p>The following message was posted to the info-dylan mailing list on October 17, 2002:</p>

<blockquote>
<p>The Gwydion Hackers are proud to announce version 2.3.9 of Gwydion
Dylan. The source tarball is available from

<blockquote>
  <a href="ftp://ftp.gwydiondylan.org/pub/gd/src/gwydion-dylan-2.3.9.tar.gz">ftp://ftp.gwydiondylan.org/pub/gd/src/gwydion-dylan-2.3.9.tar.gz</a>
</blockquote>

<p>Binary versions will appear on the FTP server during the next few
days.

<p>This is probably the last release of the unstable development
tree, and the basis for version 2.4, which shall be a high-quality
stable release.

<p>Besides the obvious ton of bugfixes, 2.3.9 provides each-subclass
slots, a rudimentary network library, greatly improved common-dylan
compliance, better performance, increased debuggability, updated
documentation and all that. This version comes with the quality
assurance library and tests kindly provided by Functional
Objects.

<p>Gwydion Dylan provides two implementations of the Dylan programming
language: Mindy and d2c. Mindy is bytecode compiler and interpreter,
and d2c is a Dylan-to-C compiler. Mindy compiles programs quickly, but
the resulting executables run slowly. On the other hand, d2c compiles
programs slowly, but they run quickly, at up to the speed of
comparable C code. Ports of Gwydion Dylan are available for all modern
platforms.

<p>Gwydion Dylan was originally written by the Gwydion Group at CMU as
part of a research project studying advanced hypercode development
environments. It is now maintained by a group of volunteers.

<p>The following online resources are available:<br>

<center>
<table>
<tr><td>Maintainers' website:<td><a href="http://www.gwydiondylan.org/">http://www.gwydiondylan.org/</a></tr>
<tr><td>Gwydion at CMU:<td><a href="http://www.cs.cmu.edu/afs/cs/project/gwydion/docs/htdocs/gwydion/">http://www.cs.cmu.edu/.../gwydion/</a></tr>
<tr><td>FTP Site:<td><a href="ftp://ftp.gwydiondylan.org/pub/gd/">ftp://ftp.gwydiondylan.org/pub/gd/</a></tr>
<tr><td>FTP Site (mirror):<td><a href="ftp://ftp.fu-berlin.de/pub/unix/languages/dylan/">ftp://ftp.fu-berlin.de/pub/unix/languages/dylan/</a></tr>
<tr><td>Bug reports:<td><a href="mailto:gd-bugs@gwydiondylan.org">gd-bugs@gwydiondylan.org</a></tr>
<tr><td>Mail to the maintainers:<td><a href="mailto:gd-hackers@gwydiondylan.org">gd-hackers@gwydiondylan.org</a></tr>
<tr><td>Newsgroup:<td><a href="news:comp.lang.dylan">comp.lang.dylan</a></tr>
</table>
</center>

<p>If you use Gwydion to any extent, you'll want subscribe to gd-hackers
so you can ask questions and report the inevitable bugs. Send a
message to <a href="mailto:gd-hackers-subscribe@gwydiondylan.org">gd-hackers-subscribe@gwydiondylan.org</a> to subscribe. If you
want to contribute code or documentation, we enthusiastically
encourage you to do so.
</blockquote>


<?php include $bottom_inc ?>
