<!doctype html public "-//W3C//DTD HTML 3.2//EN">
<!--#config errmsg="There has been an error.  Please notify webmaster@functionalobjects.com" -->
<?php $current_part = "resources";
   $title = "Functional Objects, Inc.";
   $description = "Functional Objects -- software development tools combining ease of use with power and efficiency.";
   require "../config.php3";
?>

<?php include $top_inc ?>

<h2>What is Dylan?</h2>

Dylan is a high-level dynamic object-oriented programming language
with a very exciting future.  It was originally designed by Apple
Computer, with input from industry and academic partners, as a way to
greatly enhance programmer productivity and reduce software
time-to-market.  It fills the void between Java and C++ and beats each
of them at its own game.  Dylan doesn't make you choose: it provides
ease of use <em>and</em> large-scale programming, interactivity
<em>and</em> native compilation, clean powerful maintainable software
<em>and</em> high efficiency.
<P>

From the outset, the language was designed to be powerful, consistent
and feature-rich. Dylan provides runtime safety, automatic memory
management, multiple inheritance, incremental extensibility, a module
system with multiple interface support, a pattern-driven macro system,
native platform API's, and many other advanced features.  It was
carefully designed so it can be compiled as efficiently as static
languages such as C++, and it can therefore be used for the full range
of programming tasks, from high-level scripting to intricate business
logic or powerful multi-media software.
<P>

<dl>
<dt><a href="advantages.phtml">Advantages of Dylan</a></dt>
  <dd> lists some of the benefits of Dylan compared to other languages such as Java or C++.</dd>
<dt><a href="benefits.phtml">Benefits of Dylan</a></dt>
  <dd> describes the practical benefits of Dylan's features.</dd>
<dt><a href="white-paper.phtml">Dylan White Paper</a></dt>
  <dd> describes some of the features of Dylan in more detail.</dd>
<dt><a href="com.phtml">COM Simplified</a></dt>
  <dd> describes using Dylan to simplify COM/OLE/ActiveX development.</dd>
<dt><a href="interactive-corba.phtml">Interacting with CORBA</a></dt>
  <dd> describes using Dylan for interactive CORBA development.</dd>
<dt><a href="beyond-java.phtml">Beyond Java</a></dt>
  <dd> compares using Dylan and Java for the same project.</dd>
<dt><a href="links.phtml">Links & Resources</a></dt>
  <dd> lists external Dylan links and resources.
</dl>

<?php include $bottom_inc ?>
