<!doctype html public "-//W3C//DTD HTML 3.2//EN">
<!--#config errmsg="There has been an error.  Please notify webmaster@functionalobjects.com" -->
<?php $current_part = "resources";
   $current_sub = "links";
   $title = "Functional Objects, Inc.";
   $description = "Functional Objects -- software development tools combining ease of use with power and efficiency.";
   require "../config.php3";
?>

<?php include $top_inc ?>

<h2>Dylan Links & Resources</h2>

<h3>Online Resources</h3><ul>
  <li><a href="http://groups.google.com/groups?group=comp.lang.dylan">
       Browse comp.lang.dylan on Google</a></li>
  <li><a href="http://www.ai.mit.edu/~gregs/info-dylan.html">The Info-Dylan Mailing List which is linked to comp.lang.dylan</a></li>
</ul>

<h3>Books on Dylan</h3><ul>
<!--  <li><a href="http://www.harlequin.com/products/ads/dylan/doc/drm/">
      &quot;The Dylan Reference Manual&quot; (DRM) online</a> -->
<!--
  <li><a href="http://www.harlequin.com/education/books/dylan-book/">
      &quot;Dylan Programming&quot; online</a> -->
  <li><a href="<?php echo $part_up ?>products/books.phtml#drm">
      <!-- <a href="http://www.awl.com/cseng/titles/0-201-44211-6/"> -->
      &quot;The Dylan Reference Manual&quot; (DRM) by Andrew Shalit</a>
  <li><a href="<?php echo $part_up ?>products/books.phtml#dp">
      &quot;Dylan Programming&quot; by Neal Feinberg et. al.</a>
  <li><!-- <a href="http://www.springer.de/cgi-bin/search_book.pl?link=/jour/svcat/deutsch2/comp/3540760539.html&isbn=3-540-76053-9&autor=%20I%2eD%2e%20Craig:+Programming%20in%20Dylan%20&preis=DM%2045%2e%233B%20%23A3%2019%2e50%233B%20FF%20170%2e%233B%20Lit%2049700%233B%20%2385S%20329%2e%233B%20sFr%2041%2e50%233B%20%24%2034%2e95&part="> -->
      <a href="http://www.springer-ny.com/catalog/np/mar97np/DATA/3-540-76053-9.html">
      &quot;Programming in Dylan&quot; by Iain D. Craig</a>
</ul>

<h3>Other Dylan Implementations</h3><ul>
    <li><a href="gwydion.phtml">Gwydion Dylan Development Cooperative</a>
    <li><a href="http://www.gwydiondylan.org/">Gwydion Dylan Site</a>
    <li><a href="http://marlais.sourceforge.net/">Marlais Dylan Interpreter</a>
</ul>

<h3>Other Dylan Web Sites</h3>
<ul>
    <li><a href="http://www2.shore.net/~alms/dylan/drm_errata.html">Dylan Reference Manual (DRM) errata</a>
    <li><a href="http://www.double.co.nz/dylan/">Chris Double's awesome collection of practical Dylan information.</a>
    <li><a href="http://www.pobox.com/~emk/dylan">Eric Kidd's Dylan Tutorial</a>
    <li><a href="http://www.webcom.com/haahr/dylan/">Paul Haahr's <I>A Few Things About Dylan</I></a>
    <li><a href="http://www.dylanworld.com/advocacy/Competitive.html">Stoney Ballard's competitive analysis of Dylan and C++, Objective-C and Smalltalk</a>
    <li><a href="http://sourceforge.net/projects/dylanlibs/">Dylanlibs - Dylan Code Collection</a>
    <li><a href="http://carlgay.home.comcast.net/koala/">Carl Gay's Koala Web Server</a>
    <li><a href="http://www.geocities.com/dylan_programmer/FAQ.html">Dylan Programming FAQ</a>
    <li><a href="http://www.geocities.com/dylan_programmer/index.html">Dylan Programmer</a>
    <li><a href="http://dylanpro.com/DylanExchange.html">Dylan Exchange</a>
    <li><a href="http://www.cs.indiana.edu/hyplan/jsobel/forschemers.html">Dylan Primer for Scheme Programmers</a>
    <li><a href="http://www.norvig.com/design-patterns/index.htm">Design Patterns in Dynamic Languages</a>
    <li><a href="http://www.muc.de/%7Ehoelzl/">Matthias	H&ouml;lzl's Homepage</a>
    <li><a href="http://dmoz.org/Computers/Programming/Languages/Dylan/">Open Directory Project Dylan Links</a>
    <li><a href="http://www.cetus-links.org/oo_dylan.html">Cetus Links compilation for Dylan</a>
    <li><a href="http://www.byte.com/documents/BYT20000601S0003/">Byte.COM article about Dylan</a>
    <li><a href="http://www.cs.cmu.edu/afs/cs.cmu.edu/project/ai-repository/ai/lang/others/dylan/0.html">Apple Dylan information from mid-90's</a>
<!--    <li><a href="http://www.isr.com/dylan/dylan-language/">The Dylan Language Standard</a> -->
<!--    <li><a href="http://www.basistech.com/tree/dylan/design-notes.html">Dylan Design Notes</a> -->
<!--    <li><a href="http://www.sunworld.com/swol-03-1999/swol-03-regex.html">SunWorld article about Dylan</a> -->
<!--    <li><a href="http://www.dylanworld.com">DylanWorld</a> -->
<!--    <li><a href="http://dylan.prinz.org/">The Dylan Evangelists</a> -->
</ul>

<?php include $bottom_inc ?>
