#!/bin/sh
#
#################################################################

if [ -f /u/dylan/tools/admin/env.sh ]; then 
  . /u/dylan/tools/admin/env.sh
fi

date=`date +%h%d`
time=`date +%T`

logfile="/u/dylan/tools/admin/logs/$host_name-nightly-activity-log.$date"


echo ""								>>$logfile
echo "  Processes on $host_name at $site       Time: $time"	>>$logfile
echo ""								>>$logfile
ps -a                                                   	>>$logfile
echo ""								>>$logfile
echo "--------------------------------------------------------" >>$logfile
