#!/usr/local/bin/perl
#
# Author: Shri Amit(amit)
#
# Purpose: This script calls proc-report on the following
#	   machines: bakura, banshee, phanton (1cc)
#		     zaphod, casper (long)
#		     meteor (menlo)
#		     bright, skookum (seattle)
##########################################################

$scriptsdir = "/u/dylan/tools/scripts";

$date = `date`;
print "\nStarted running: $date";

print "\nAttempting bakura";
system("$scriptsdir/proc-report bakura");

print "\nAttempting banshee";
system("$scriptsdir/proc-report banshee");

print "\nAttempting phantom";
system("$scriptsdir/proc-report phantom");

print "\nAttempting zaphod";
system("$scriptsdir/proc-report zaphod.long.harlequin.co.uk");

print "\nAttempting casper";
system("$scriptsdir/proc-report casper.long.harlequin.co.uk");

print "\nAttempting meteor";
system("$scriptsdir/proc-report meteor.menlo.harlequin.com");

print "\nAttempting bright";
system("$scriptsdir/proc-report bright.seattle.harlequin.com");

print "\nAttempting skookum";
system("$scriptsdir/proc-report skookum.seattle.harlequin.com");

print "\nEnd of script call-proc-report";
$date = `date`;
print "\nFinished running: $date";

