#!/bin/sh
sed -e '/^\/FMFAILURE/{
:loop
n
/show FMshowpage/{
s/^/%/
s/$/ % Uncomment this line for traditional Frame failure behaviour/
a\
	pop % Comment this line for traditional Frame failure behaviour
}
/FMquit/{s/^/%/
s/$/ % Uncomment this line for traditional Frame failure behaviour/
b exit
}
b loop
}
:exit' $@
