#!/bin/sh
#
# Dylan cross reference
#
# List any number of Dylan source files as the arguments.  If no arguments
# are given, "lib-files" will be used to get the file names for the library
# in the current directory.  A cross-reference report will be written to
# standard output.  Identifiers are listed alphabetically in the first
# column, with the second and third columns showing the file name and
# definition name where it is referenced.
#
# Typical usage example:
#	dylan-xref *.dylan > xref.text
# writes to file "xref.text" a cross-reference listing showing where each
# defined name is referenced.
#
# See also the comments in the "dxref" script for how it can be used 
# directly, providing more control over what should be displayed.

#----

if [ $# -gt 0 ]
then
  files="$@"
else
  files=`/u/dylan/tools/scripts/lib-files`
fi
# First "dtags" collects a list of the defined names, and then "dxref"
# scans the files again, looking for references to those names.
/u/dylan/tools/gnuemacs/dtags -o -  -quiet $files | \
  /u/dylan/tools/scripts/dxref -names -  $files | sort -f -u
