#!/bin/sh

#HOPEPORT=9042
#HOPEHOST=wratting
#HOPESHADOWS=/nfs/noggin/usr/users/keith/HOPE/src
#export HOPESHADOWS
#export HOPEPORT HOPEHOST 
#exec /nfs/noggin/usr/users/keith/bin/hope "$@"

#HOPEPORT=9102
#export HOPEPORT

if [ -n "$DEBUG_DYLAN_HOPE" ]; then
  echo DEBUG_DYLAN_HOPE is set in environment. Echoing arguments to hope call.
  echo would invoke
  echo /usr/local/bin/hope "$@"
  echo
  while [ -n "$1" ]; do
	echo ARG: "$1"
	shift
  done
  echo
  echo END OF ARGUMENTS. Exiting _without_ executing hope command.
  exit 1
fi
exec /usr/local/bin/hope "$@"

# eof
