#!/bin/sh
## Extract a compound name from the local version file if it exists

## Revision by amit on Jan 13 97. Now the compound and the branch ##
## are returned                                                   ##
##
if [ -f .version ]; then
  compound=`head -1 .version | sed -e 's/^\(.*\),.*,.*,.*,.*,.*$/\1/'`
  branch=`head -1 .version | cut -f2 -d","`
  echo "$compound($branch)"

fi

# eof
