#!/bin/sh

# Report on the status of a compound.

compound=""
hope_options=""

# This quoting hackery is an attempt to preserve grouping

while [ $# -gt 0 ]; do
  case $1 in
    -c | -comp | -compound) 
      compound=$2; shift 2
      ;;
    -ci-reason)
      hope_options="$hope_options $1 \"$2\""; shift 2
      # hope_options="$hope_options $1 $2"; shift 2
      ;;
    -version | -branch)
      hope_options="$hope_options $1 \"$2\""; shift 2
      ;;
    -*)
      echo "$script: unrecognised option $1"
      exit 1
      ;;
    *)        
      break
      ;;
  esac
done

files=$*

if [ "$files" = "" ]; then
  if [ "$compound" = "" ]; then
    compound=`dylan-local-compound`
  fi
  if [ "$compound" = "" ]; then
    echo "$script: error - no compound located"
    exit 1
  fi
  eval "dylan-hope status -comp $compound $hope_options"  
  exit 0
fi

for file in $files; do
  name=`basename $file`
  dir=`dirname $file`
  (cd $dir
   if [ "$compound" = "" ]; then
     compound=`dylan-local-compound`
   fi
   if [ "$compound" = "" ]; then
     echo "$script: error - no compound found for $file"
   fi
   eval "dylan-hope status -comp $compound $hope_options -unit $name" 
  )
done

# eof
