#!/bin/sh

# Returns 0 if in hope, 1 otherwise

file=$1
name=`basename $file`
dir=`dirname $file`
version=$dir/.version

if [ -f $version ]; then
  eval grep "::=$name::=" $version > /dev/null
  case $? in
    0) exit 0;;
    1) exit 1;;
    *) exit 2;;
  esac
else
  exit 1
fi

# eof
