#!/bin/sh 

# Remove the given objects from hope

script=`basename $0`
usage="usage: $script <stuff>"

compound=""
hope_options=""

while [ $# -gt 0 ]; do
  case $1 in
    -c | -comp | -compound) 
      compound=$2; shift 2
      ;;
    -claim | -reason | -working-file | -version | -branch)
      hope_options="$hope_options $1 $2"; shift 2
      ;;
    -*)
      echo "$script: unrecognised option $1"
      exit 1
      ;;
    *)        
      break
      ;;
  esac
done

files=$*

if [ "$compound" = "" ]; then
  compound=`dylan-local-compound`
  if [ "$compound" = "" ]; then
    echo "$script: error - no compound specified and no version file located"
    exit 1
  else
    echo "$script: taking compound $compound from version file"
  fi
fi

if [ "$files" = "" ]; then
  echo "$script: working on compound $compound"
  dylan-hope co -comp $compound -recursive $hope_options
else
  echo "$script: working on $files from $compound"
  for file in $files; do
    dylan-hope co -comp $compound -recursive $hope_options -u $file
  done
fi

## eof
