#!/usr/local/bin/bash

if [ $# = 1 ]; then
  reason=$1
else
  reason="editing"
fi
compound=`dylan-local-compound`
units=`echo *.dylan *.lid`
hopified_units=`unitify $units`

hope co -claim soft -reason \"$reason\" -compound $compound $hopified_units
