#!/bin/sh

script=`basename $0`
scriptdir=`dirname $0`

PATH="$scriptdir:/usr/ucb:$PATH"
export PATH
USER=`whoami`
export USER


echo "Nightly build log for `date` on `hostname`"
echo "Build instigated by `whoami`"
echo "PATH is $PATH"
echo "USER is $USER"
echo ""

echo "$script: synching sources"
echo ""
sync-dylan-sources

echo ""
echo "$script: building the translator"
echo ""
build-translator

echo ""
echo "$script: building the compiler"
echo ""
build-compiler
echo ""

exit 0

# eof
