#!/bin/sh

# Sync with hope

dylandir=/u/dylan
#version="-date \"94/05/29\""
version=""
compounds="translator dw lib project"

cd $dylandir

echo "Working in `pwd`"

for compound in $compounds; do
  echo "Synching DYLAN$compound"
  dylan-co $version -not-linked -working-file skip -missing-dir create -extra-files delete -compound "DYLAN$compound"
done

# eof
