#!/bin/sh
# Convert an X windows header file to Dylan C-FFI declarations.
# Usage:
#   x-to-dylan -module x foo.h foo.dylan
# or:
#   x-to-dylan -module x -odir . *.h
#
/u/dylan/local/gema -f ../xlib/patterns.pat -f ../xlib/motif.pat \
	-f ../xlib/modcopyr.pat   -exclude ../xlib/obsolete.text \
	-otyp .dylan   "$@"
