module: dylan-user
copyright: See LICENSE file in this distribution.

define library gdkpixbuf
  use dylan;
  use common-dylan;
  use c-ffi;
  use gobject-glue;
  use gobject;
  use gio;
  use gmodule;
  use glib;

  export gdkpixbuf;
end library;

define module gdkpixbuf
  use dylan;
  use common-dylan;
  use c-ffi;
  use gobject-glue;
  use gobject;
  use gio;
  use gmodule;
  use glib;

  export
    gdk-pixbuf-error-quark,
    <GdkPixdataType*>,
    <GdkPixdataType>,
    $GDK-PIXDATA-ENCODING-MASK,
    $GDK-PIXDATA-ENCODING-RLE,
    $GDK-PIXDATA-ENCODING-RAW,
    $GDK-PIXDATA-SAMPLE-WIDTH-MASK,
    $GDK-PIXDATA-SAMPLE-WIDTH-8,
    $GDK-PIXDATA-COLOR-TYPE-MASK,
    $GDK-PIXDATA-COLOR-TYPE-RGBA,
    $GDK-PIXDATA-COLOR-TYPE-RGB,
    <GdkPixdataDumpType*>,
    <GdkPixdataDumpType>,
    $GDK-PIXDATA-DUMP-RLE-DECODER,
    $GDK-PIXDATA-DUMP-CONST,
    $GDK-PIXDATA-DUMP-STATIC,
    $GDK-PIXDATA-DUMP-CTYPES,
    $GDK-PIXDATA-DUMP-GTYPES,
    $GDK-PIXDATA-DUMP-MACROS,
    $GDK-PIXDATA-DUMP-PIXDATA-STRUCT,
    $GDK-PIXDATA-DUMP-PIXDATA-STREAM,
    gdk-pixdata-to-csource,
    gdk-pixdata-serialize,
    gdk-pixdata-deserialize,
    gdkpixdata-pixel-data-setter,
    gdkpixdata-pixel-data,
    gdkpixdata-height-setter,
    gdkpixdata-height,
    gdkpixdata-width-setter,
    gdkpixdata-width,
    gdkpixdata-rowstride-setter,
    gdkpixdata-rowstride,
    gdkpixdata-pixdata-type-setter,
    gdkpixdata-pixdata-type,
    gdkpixdata-length-setter,
    gdkpixdata-length,
    gdkpixdata-magic-setter,
    gdkpixdata-magic,
    <GdkPixdata>,
    <GdkPixbufSimpleAnimIter*>,
    <GdkPixbufSimpleAnimIter>,
    <GdkPixbufSimpleAnimClass>,
    gdk-pixbuf-simple-anim-set-loop,
    gdk-pixbuf-simple-anim-get-loop,
    gdk-pixbuf-simple-anim-add-frame,
    gdk-pixbuf-simple-anim-new,
    @pixbufsimpleanim-loop-setter,
    @pixbufsimpleanim-loop,
    <GdkPixbufSimpleAnim*>,
    <GdkPixbufSimpleAnim>,
    <GdkPixbufRotation*>,
    <GdkPixbufRotation>,
    $GDK-PIXBUF-ROTATE-CLOCKWISE,
    $GDK-PIXBUF-ROTATE-UPSIDEDOWN,
    $GDK-PIXBUF-ROTATE-COUNTERCLOCKWISE,
    $GDK-PIXBUF-ROTATE-NONE,
    gdkpixbufloaderclass-closed,
    gdkpixbufloaderclass-area-updated,
    gdkpixbufloaderclass-area-prepared,
    gdkpixbufloaderclass-size-prepared,
    gdkpixbufloaderclass-parent-class,
    <GdkPixbufLoaderClass>,
    gdk-pixbuf-loader-write,
    gdk-pixbuf-loader-set-size,
    gdk-pixbuf-loader-get-pixbuf,
    gdk-pixbuf-loader-get-format,
    gdk-pixbuf-loader-get-animation,
    gdk-pixbuf-loader-close,
    gdk-pixbuf-loader-new-with-type,
    gdk-pixbuf-loader-new-with-mime-type,
    gdk-pixbuf-loader-new,
    <GdkPixbufLoader*>,
    gdkpixbufloader-priv,
    gdkpixbufloader-parent-instance,
    <GdkPixbufLoader>,
    gdk-pixbuf-format-set-disabled,
    gdk-pixbuf-format-is-writable,
    gdk-pixbuf-format-is-scalable,
    gdk-pixbuf-format-is-disabled,
    gdk-pixbuf-format-get-name,
    gdk-pixbuf-format-get-mime-types,
    gdk-pixbuf-format-get-license,
    gdk-pixbuf-format-get-extensions,
    gdk-pixbuf-format-get-description,
    gdk-pixbuf-format-free,
    gdk-pixbuf-format-copy,
    <GdkPixbufFormat>,
    <GdkPixbufError*>,
    <GdkPixbufError>,
    $GDK-PIXBUF-ERROR-FAILED,
    $GDK-PIXBUF-ERROR-UNSUPPORTED-OPERATION,
    $GDK-PIXBUF-ERROR-UNKNOWN-TYPE,
    $GDK-PIXBUF-ERROR-BAD-OPTION,
    $GDK-PIXBUF-ERROR-INSUFFICIENT-MEMORY,
    $GDK-PIXBUF-ERROR-CORRUPT-IMAGE,
    gdk-pixbuf-animation-iter-on-currently-loading-frame,
    gdk-pixbuf-animation-iter-get-pixbuf,
    gdk-pixbuf-animation-iter-get-delay-time,
    gdk-pixbuf-animation-iter-advance,
    <GdkPixbufAnimationIter*>,
    <GdkPixbufAnimationIter>,
    gdk-pixbuf-animation-is-static-image,
    gdk-pixbuf-animation-get-width,
    gdk-pixbuf-animation-get-static-image,
    gdk-pixbuf-animation-get-iter,
    gdk-pixbuf-animation-get-height,
    gdk-pixbuf-animation-new-from-stream-async,
    gdk-pixbuf-animation-new-from-stream-finish,
    gdk-pixbuf-animation-new-from-stream,
    gdk-pixbuf-animation-new-from-resource,
    gdk-pixbuf-animation-new-from-file,
    <GdkPixbufAnimation*>,
    <GdkPixbufAnimation>,
    <GdkPixbufAlphaMode*>,
    <GdkPixbufAlphaMode>,
    $GDK-PIXBUF-ALPHA-FULL,
    $GDK-PIXBUF-ALPHA-BILEVEL,
    gdk-pixbuf-scale-simple,
    gdk-pixbuf-scale,
    gdk-pixbuf-savev,
    gdk-pixbuf-save-to-callbackv,
    gdk-pixbuf-save-to-bufferv,
    gdk-pixbuf-saturate-and-pixelate,
    gdk-pixbuf-rotate-simple,
    gdk-pixbuf-new-subpixbuf,
    gdk-pixbuf-get-width,
    gdk-pixbuf-get-rowstride,
    gdk-pixbuf-get-pixels-with-length,
    gdk-pixbuf-get-option,
    gdk-pixbuf-get-n-channels,
    gdk-pixbuf-get-height,
    gdk-pixbuf-get-has-alpha,
    gdk-pixbuf-get-colorspace,
    gdk-pixbuf-get-byte-length,
    gdk-pixbuf-get-bits-per-sample,
    gdk-pixbuf-flip,
    gdk-pixbuf-fill,
    gdk-pixbuf-copy-area,
    gdk-pixbuf-copy,
    gdk-pixbuf-composite-color-simple,
    gdk-pixbuf-composite-color,
    gdk-pixbuf-composite,
    gdk-pixbuf-apply-embedded-orientation,
    gdk-pixbuf-add-alpha,
    gdk-pixbuf-save-to-stream-finish,
    gdk-pixbuf-new-from-stream-at-scale-async,
    gdk-pixbuf-new-from-stream-async,
    gdk-pixbuf-gettext,
    gdk-pixbuf-get-formats,
    gdk-pixbuf-get-file-info,
    gdk-pixbuf-from-pixdata,
    gdk-pixbuf-new-from-xpm-data,
    gdk-pixbuf-new-from-stream-finish,
    gdk-pixbuf-new-from-stream-at-scale,
    gdk-pixbuf-new-from-stream,
    gdk-pixbuf-new-from-resource-at-scale,
    gdk-pixbuf-new-from-resource,
    gdk-pixbuf-new-from-inline,
    gdk-pixbuf-new-from-file-at-size,
    gdk-pixbuf-new-from-file-at-scale,
    gdk-pixbuf-new-from-file,
    gdk-pixbuf-new-from-data,
    gdk-pixbuf-new,
    @pixbuf-width-setter,
    @pixbuf-width,
    @pixbuf-rowstride-setter,
    @pixbuf-rowstride,
    @pixbuf-pixels-setter,
    @pixbuf-pixels,
    @pixbuf-n-channels-setter,
    @pixbuf-n-channels,
    @pixbuf-height-setter,
    @pixbuf-height,
    @pixbuf-has-alpha-setter,
    @pixbuf-has-alpha,
    @pixbuf-colorspace-setter,
    @pixbuf-colorspace,
    @pixbuf-bits-per-sample-setter,
    @pixbuf-bits-per-sample,
    <GdkPixbuf*>,
    <GdkPixbuf>,
    $PIXDATA-HEADER-LENGTH,
    $PIXBUF-VERSION,
    $PIXBUF-MINOR,
    $PIXBUF-MICRO,
    $PIXBUF-MAJOR,
    $PIXBUF-MAGIC-NUMBER,
    $PIXBUF-FEATURES-H,
    <GdkInterpType*>,
    <GdkInterpType>,
    $GDK-INTERP-HYPER,
    $GDK-INTERP-BILINEAR,
    $GDK-INTERP-TILES,
    $GDK-INTERP-NEAREST,
    <GdkColorspace*>,
    <GdkColorspace>,
    $GDK-COLORSPACE-RGB;
end module;
