module: dylan-user
copyright: See LICENSE file in this distribution.

define library gdkpixbuf
  use dylan;
  use common-dylan;
  use c-ffi;
  use glib;
  use gmodule;
  use gobject;
  use gio;
  use gobject;
  use glib;

  export gdkpixbuf;
  export gdkpixbuf-properties;
end library;

define module gdkpixbuf
  use dylan;
  use common-dylan;
  use c-ffi;
  use gobject-glue;
  use glib;
  use gmodule;
  use gobject;
  use gio;
  use gobject;
  use glib;

  export
    gdk-pixbuf-error-quark,
    <GdkPixdataType*>,
    <GdkPixdataType>,
    $gdk-pixdata-encoding-mask,
    $gdk-pixdata-encoding-rle,
    $gdk-pixdata-encoding-raw,
    $gdk-pixdata-sample-width-mask,
    $gdk-pixdata-sample-width-8,
    $gdk-pixdata-color-type-mask,
    $gdk-pixdata-color-type-rgba,
    $gdk-pixdata-color-type-rgb,
    <GdkPixdataDumpType*>,
    <GdkPixdataDumpType>,
    $gdk-pixdata-dump-rle-decoder,
    $gdk-pixdata-dump-const,
    $gdk-pixdata-dump-static,
    $gdk-pixdata-dump-ctypes,
    $gdk-pixdata-dump-gtypes,
    $gdk-pixdata-dump-macros,
    $gdk-pixdata-dump-pixdata-struct,
    $gdk-pixdata-dump-pixdata-stream,
    gdk-pixdata-to-csource,
    gdk-pixdata-serialize,
    gdk-pixdata-deserialize,
    gdk-pixdata-pixel-data-setter,
    gdk-pixdata-pixel-data,
    gdk-pixdata-height-setter,
    gdk-pixdata-height,
    gdk-pixdata-width-setter,
    gdk-pixdata-width,
    gdk-pixdata-rowstride-setter,
    gdk-pixdata-rowstride,
    gdk-pixdata-pixdata-type-setter,
    gdk-pixdata-pixdata-type,
    gdk-pixdata-length-setter,
    gdk-pixdata-length,
    gdk-pixdata-magic-setter,
    gdk-pixdata-magic,
    <GdkPixdata>,
    <GdkPixbufSimpleAnimIter*>,
    <GdkPixbufSimpleAnimIter>,
    <GdkPixbufSimpleAnimClass>,
    gdk-pixbuf-simple-anim-set-loop,
    gdk-pixbuf-simple-anim-get-loop,
    gdk-pixbuf-simple-anim-add-frame,
    gdk-pixbuf-simple-anim-new,
    <GdkPixbufSimpleAnim*>,
    <GdkPixbufSimpleAnim>,
    <GdkPixbufRotation*>,
    <GdkPixbufRotation>,
    $gdk-pixbuf-rotate-clockwise,
    $gdk-pixbuf-rotate-upsidedown,
    $gdk-pixbuf-rotate-counterclockwise,
    $gdk-pixbuf-rotate-none,
    gdk-pixbuf-loader-class-closed,
    gdk-pixbuf-loader-class-area-updated,
    gdk-pixbuf-loader-class-area-prepared,
    gdk-pixbuf-loader-class-size-prepared,
    gdk-pixbuf-loader-class-parent-class,
    <GdkPixbufLoaderClass>,
    gdk-pixbuf-loader-write,
    gdk-pixbuf-loader-set-size,
    gdk-pixbuf-loader-get-pixbuf,
    gdk-pixbuf-loader-get-format,
    gdk-pixbuf-loader-get-animation,
    gdk-pixbuf-loader-close,
    gdk-pixbuf-loader-new-with-type,
    gdk-pixbuf-loader-new-with-mime-type,
    gdk-pixbuf-loader-new,
    <GdkPixbufLoader*>,
    gdk-pixbuf-loader-priv,
    gdk-pixbuf-loader-parent-instance,
    <GdkPixbufLoader>,
    gdk-pixbuf-format-set-disabled,
    gdk-pixbuf-format-is-writable,
    gdk-pixbuf-format-is-scalable,
    gdk-pixbuf-format-is-disabled,
    gdk-pixbuf-format-get-name,
    gdk-pixbuf-format-get-mime-types,
    gdk-pixbuf-format-get-license,
    gdk-pixbuf-format-get-extensions,
    gdk-pixbuf-format-get-description,
    gdk-pixbuf-format-free,
    gdk-pixbuf-format-copy,
    <GdkPixbufFormat>,
    <GdkPixbufError*>,
    <GdkPixbufError>,
    $gdk-pixbuf-error-failed,
    $gdk-pixbuf-error-unsupported-operation,
    $gdk-pixbuf-error-unknown-type,
    $gdk-pixbuf-error-bad-option,
    $gdk-pixbuf-error-insufficient-memory,
    $gdk-pixbuf-error-corrupt-image,
    gdk-pixbuf-animation-iter-on-currently-loading-frame,
    gdk-pixbuf-animation-iter-get-pixbuf,
    gdk-pixbuf-animation-iter-get-delay-time,
    gdk-pixbuf-animation-iter-advance,
    <GdkPixbufAnimationIter*>,
    <GdkPixbufAnimationIter>,
    gdk-pixbuf-animation-is-static-image,
    gdk-pixbuf-animation-get-width,
    gdk-pixbuf-animation-get-static-image,
    gdk-pixbuf-animation-get-iter,
    gdk-pixbuf-animation-get-height,
    gdk-pixbuf-animation-new-from-file,
    <GdkPixbufAnimation*>,
    <GdkPixbufAnimation>,
    <GdkPixbufAlphaMode*>,
    <GdkPixbufAlphaMode>,
    $gdk-pixbuf-alpha-full,
    $gdk-pixbuf-alpha-bilevel,
    gdk-pixbuf-scale-simple,
    gdk-pixbuf-scale,
    gdk-pixbuf-savev,
    gdk-pixbuf-save-to-callbackv,
    gdk-pixbuf-save-to-bufferv,
    gdk-pixbuf-saturate-and-pixelate,
    gdk-pixbuf-rotate-simple,
    gdk-pixbuf-new-subpixbuf,
    gdk-pixbuf-get-width,
    gdk-pixbuf-get-rowstride,
    gdk-pixbuf-get-pixels-with-length,
    gdk-pixbuf-get-option,
    gdk-pixbuf-get-n-channels,
    gdk-pixbuf-get-height,
    gdk-pixbuf-get-has-alpha,
    gdk-pixbuf-get-colorspace,
    gdk-pixbuf-get-byte-length,
    gdk-pixbuf-get-bits-per-sample,
    gdk-pixbuf-flip,
    gdk-pixbuf-fill,
    gdk-pixbuf-copy-area,
    gdk-pixbuf-copy,
    gdk-pixbuf-composite-color-simple,
    gdk-pixbuf-composite-color,
    gdk-pixbuf-composite,
    gdk-pixbuf-apply-embedded-orientation,
    gdk-pixbuf-add-alpha,
    gdk-pixbuf-save-to-stream-finish,
    gdk-pixbuf-new-from-stream-at-scale-async,
    gdk-pixbuf-new-from-stream-async,
    gdk-pixbuf-gettext,
    gdk-pixbuf-get-formats,
    gdk-pixbuf-get-file-info,
    gdk-pixbuf-from-pixdata,
    gdk-pixbuf-new-from-xpm-data,
    gdk-pixbuf-new-from-stream-finish,
    gdk-pixbuf-new-from-stream-at-scale,
    gdk-pixbuf-new-from-stream,
    gdk-pixbuf-new-from-resource-at-scale,
    gdk-pixbuf-new-from-resource,
    gdk-pixbuf-new-from-inline,
    gdk-pixbuf-new-from-file-at-size,
    gdk-pixbuf-new-from-file-at-scale,
    gdk-pixbuf-new-from-file,
    gdk-pixbuf-new-from-data,
    gdk-pixbuf-new,
    <GdkPixbuf*>,
    <GdkPixbuf>,
    $pixdata-header-length,
    $pixbuf-version,
    $pixbuf-minor,
    $pixbuf-micro,
    $pixbuf-major,
    $pixbuf-magic-number,
    $pixbuf-features-h,
    <GdkInterpType*>,
    <GdkInterpType>,
    $gdk-interp-hyper,
    $gdk-interp-bilinear,
    $gdk-interp-tiles,
    $gdk-interp-nearest,
    <GdkColorspace*>,
    <GdkColorspace>,
    $gdk-colorspace-rgb;
end module;

define module gdkpixbuf-properties
  use gdkpixbuf;
  use gobject-glue;

  export
    @loop-setter,
    @loop,
    @width-setter,
    @width,
    @rowstride-setter,
    @rowstride,
    @pixels-setter,
    @pixels,
    @n-channels-setter,
    @n-channels,
    @height-setter,
    @height,
    @has-alpha-setter,
    @has-alpha,
    @colorspace-setter,
    @colorspace,
    @bits-per-sample-setter,
    @bits-per-sample;
end module;
