Origin:     OMG-IDL
IDL-file:   ../ir.idl
Prefix: ir
Include: ..
Main: yes
Protocol:      yes
Stubs:	yes
Skeletons: no
Libraries: functional-dylan,corba-protocol,orb-core
Modules: functional-dylan,corba-protocol,orb-core
