#!/bin/sh
# Convert an X windows header file to Dylan C-FFI declarations.
# Usage:
#   x-to-dylan -module x foo.h foo.dylan
# or:
#   x-to-dylan -module x -odir . *.h
#
/u/dylan/local/gema -f ../glib/patterns.pat \
	-f ../glib/modcopyr.pat -exclude obsolete.text \
        -rename renamings.text \
	-otyp .dylan   "$@"
