#!/bin/bash

make-runtime

link-dylan

repeat link common-dylan functional-dylan collections io system generic-arithmetic big-integers source-records file-source-records release-info internal-release-info binary-manager binary-builder coff-manager coff-builder build-system elf-linker ccl-linker linker-support gnu-linker

link-build

pushd $FUNCTIONAL_DEVELOPER_USER_INSTALL
mkdir lib/boot
cp -pf lib/* lib/boot/

cd $FUNCTIONAL_DEVELOPER_USER_BUILD
rm */*.s.o
for f in *; do if [ -f $f/dylanmakefile.mkf ]; then sed -e 's!\\!/!g' $f/dylanmakefile.mkf > $f/dylanmakefile.mkf.new; mv $f/dylanmakefile.mkf.new $f/dylanmakefile.mkf; fi; done

BOOT=$FUNCTIONAL_DEVELOPER_USER_INSTALL/lib/boot
LD_LIBRARY_PATH=$BOOT $BOOT/build elf assemble-all basic-pentium-dw.exe

popd
