#!/bin/bash

#   Usage:    config -r release-root -c compiler-root -b personal-root -s sources-root

#   Example:  Build a Gen4 compiler using a Gen3 compiler
#            config -rc /home/nosa/dylan/linux/b3 -b /home/nosa/dylan/linux/b4 -s /home/nosa/dylan/linux

function find_compiler ()
{
  dylan_compile="$1/bin/fdcompile"
  [ -f $1/bin/fdcompile ] || dylan_compile="$1/bin/basic-pentium-dw"
  dylan_compile_options="-save -messages=internal"
  build="$1/bin/build"
  export dylan_compile dylan_compile_options build
}

export OPEN_DYLAN_SYSTEM_DEVELOPER="yes"

while [ "$#" -ne 0 ]; do
  case $1 in

   -r) export OPEN_DYLAN_RELEASE="$2" ;;

   -b) export OPEN_DYLAN_USER_BUILD="$2/build"
       export OPEN_DYLAN_USER_INSTALL="$2"
       cd $2 ;;

   -s) export OPEN_DYLAN_USER_SOURCES="$2/sources"
       export OPEN_DYLAN_USER_REGISTRIES="$2/sources/registry" ;;

   -c) find_compiler $2 ;;

   -rc) find_compiler $2
	export OPEN_DYLAN_RELEASE="$2" ;;

   -rs) export OPEN_DYLAN_RELEASE="$2"
        export OPEN_DYLAN_USER_SOURCES="$2/sources"
        export OPEN_DYLAN_USER_REGISTRIES="$2/sources/registry" ;;

   -rcs) find_compiler $2
         export OPEN_DYLAN_RELEASE=$2
         export OPEN_DYLAN_USER_SOURCES="$2/sources"
         export OPEN_DYLAN_USER_REGISTRIES="$2/sources/registry" ;;

     *) echo Invalid command line option -  $option
        exit ;;
  esac
  shift
  shift
done

echo Settings...
printenv | grep OPEN_DYLAN
printenv | grep dylan_compile
