set-write-databases? true
compile -force-parse operating-system
save -export-only operating-system
compile -force-parse date
save -export-only date
compile -force-parse file-system
save -export-only file-system
compile -force-parse streams
save -export-only streams
compile -force-parse print
save -export-only print
compile -force-parse format
save -export-only format
compile -force-parse standard-io
save -export-only standard-io
compile -force-parse format-out
save -export-only format-out
exit
