#!/usr/local/bin/bash
# maps machine to dylan's platform directory names
# add to this as we add more platforms
# 
# what about x86-win32??
#
# Last modified by amit on July 25 1996 to
# add HP to the list of supported platforms
##################################################
here=`dirname $0`
machine=`/u/dylan/admin/scripts/machine-config`
case "{$machine}" in
 *sparc-sunos4*) 	
  echo sparc-sunos4 ;;
 *sparc-solaris2*)
  echo sparc-solaris2 ;;
 *alpha*osfV3*)
  echo alpha-osf3 ;;
 *irix5*)
  echo  mips-irix5  ;;
 *hppa1.0-hp-hpux*)
  echo hp-hpux ;;
 *)
  echo unsupported platform ;; 
esac
