#!/usr/local/bin/bash
#      Script: kansas
#      Author: Andy Armstrong
usage=" Usage: $0 -i <Image> -p <Personal Root> -r <Root> -l <Platform> -e"
# Opts & Flgs: -r: Root of sources, default:
#                          pentium back end: /u/dylan/releases/kansas
#              -p: Personal Root, default: none
#              -i: Image, default: lw+dylan+dfmc-pc-$platform
#              -e: Invoke image with pre-loaded dfmc environment.
#
#    Synopsis: A platform independent and trouble free way to invoke
#              the kansas dfmc images. Sets up the required env. variables
#              and executes the appropriate binary image.
#              Note that any extra arguments specified shall get passed
#              along to the image.
######################################################################
## Application exit status legend ##
##  1: Personal Root not specified
##  2: Unsupported host platform

## Parse the command line and check incorrect usage ##
##
dylanroot="/u/dylan"
scriptsdir="$dylanroot/admin/scripts"
root=""
extra_args=""
while [ "$#" -ne 0 ]; do
  case $1 in
      -r | -root) shift
                  root="$1" ;;
        -p | -pr) shift
	          personal_root="$1" ;;
     -i | -image) shift
                  image="$1" ;;
              -e) env=Yes ;;
               *) extra_args="$extra_args $1";;
  esac
  shift
done

## Ensure personal root, and that host and target ##
## platforms are supported                        ##
##
curr_dir=`pwd`
cd `dirname $0`/..
default_root=`pwd`

## Useful to set root explicitely since it is a very ##
## commonly used variable and name collisions may    ##
## occur if it get exported or re-exported in some   ##
## bash environment                                  ##
##
case $root in
    "") root=$default_root ;;
     *) ;;
esac
env=${env:-No}
platform=`$scriptsdir/dylan-platform`
cd $curr_dir

case $personal_root in
   "") echo "$0: Error - A personal root must be specified"
       exit 1;;
    *) ;;
esac
case $platform in
    sparc-solaris2 | sparc-sunos4 | alpha-osf3) ;;
    *) echo "$0 - Error - unsupported host platform: $platform"
       exit 3 ;;
esac

case $env in
    Yes) image=${image:-$root/install/$platform/bin/lw+dylan+dfmc+env-pc-$platform} ;;
     No) ;;
esac

image=${image:-$root/install/$platform/bin/lw+dylan+dfmc-pc-$platform}
images_used_file=$root/admin/logs/images-used.log
echo "The Image being used is: $image" >> $images_used_file

## source dfmc env and then execute the image ##
##
echo Setting up the dfmc environment variables
source $scriptsdir/kan-env.bash -r $root -p $personal_root -l pentium
case $extra_args in
    "") ;;
     *) echo The image is being executed with the following arguments:
        echo "   $extra_args" ;;
esac
echo Executing the image, please standby ...
exec $image $extra_args

#eof
