#!/usr/local/bin/bash
#      Script: lw-dylan
#      Author: Shri Amit(amit)
usage=" Usage: $0 -r <Root>"
# Opts & Flgs: -r: <Root>, default: /u/dylan/releases/kan
#    Synopsis: A platform independent and trouble free way to invoke
#              the emulator and environment images. Any extra arguments
#              shall be passed along to the image.
######################################################################

## Parse the command line and check incorrect usage ##
##
dylanroot="/u/dylan"
scriptsdir="$dylanroot/admin/scripts"
extra_args=""
while [ "$#" -ne 0 ]; do
  case $1 in
 -r | -root) shift
             root="$1" ;;
          *) extra_args="$extra_args $1";;
  esac
  shift
done


## Set the defaults and invoke the image ##
##
default_root="$dylanroot/releases/kan"
root=${root:-$default_root}
platform=`$scriptsdir/dylan-platform`
image=$root/local/lw+dylan-$platform
images_used_file=$root/admin/logs/images-used.log
echo "The Image being used is: $image" >> $images_used_file

## Get the absolute pathname so that the emulator does    ## 
## not get confused and load sources from the wrong place ##
##
curr_dir=`pwd`
cd $root
absolute_root=`pwd`
cd $curr_dir
export DYLAN_ROOT=$absolute_root
export TRUNK_SYSTEM_ROOT="$absolute_root/"
case $extra_args in
    "") ;;
     *) echo The image is being executed with the following arguments:
        echo "   $extra_args" ;;
esac
echo Executing the image, please standby ...
exec $image $extra_args

#eof
