#! /usr/local/bin/bash

# promote-compiler  [no args]
#  by Doug Dodds

# Promote the subset of the Dylan sources that make up the compiler

/u/dylan/admin/scripts/promote \
 D-app                         \
 D-corba                       \
 D-collections                 \
 D-dfmc                        \
 D-harp                        \
 D-io                          \
 D-ole                         \
 D-network                     \
 D-project-manager             \
 D-registry                    \
 D-system                      \
 D-win32                       \
 D-build-x86-win32             \
 D-install-x86-win32           \
 D-lib-big-integers            \
 D-lib-bit-set                 \
 D-lib-bit-vector              \
 D-lib-build-system            \
 D-lib-byte-vector             \
 D-lib-c-ffi                   \
 D-lib-c-lexer                 \
 D-lib-collectors              \
 D-lib-command-shell           \
 D-lib-common-dylan            \
 D-lib-common-extensions       \
 D-lib-date                    \
 D-lib-disasm                  \
 D-lib-dispatch-profiler       \
 D-lib-dood                    \
 D-lib-dylan                   \
 D-lib-file-system             \
 D-lib-format                  \
 D-lib-format-out              \
 D-lib-generic-arithmetic      \
 D-lib-grammar-compiler        \
 D-lib-functional-dylan         \
 D-lib-functional-extensions    \
 D-lib-licensing               \
 D-lib-linker-support          \
 D-lib-memory-manager          \
 D-lib-metering                \
 D-lib-motley                  \
 D-lib-operating-system        \
 D-lib-parser-generator        \
 D-lib-parser-run-time         \
 D-lib-pentium-run-time        \
 D-lib-plists                  \
 D-lib-ppml                    \
 D-lib-print                   \
 D-lib-release-info            \
 D-lib-set                     \
 D-lib-settings                \
 D-lib-source-records          \
 D-lib-standard-io             \
 D-lib-streams                 \
 D-lib-t-lists                 \
 D-lib-table-extensions        \
 D-lib-threads                 \
 D-lib-transcendentals         \
 D-lib-variable-search         \
 D-lib-walker
