#! /usr/local/bin/bash

# promote-rest  [no args]
#  by Doug Dodds

# Promotes the "rest" of the Dylan sources not involved in the compiler

/u/dylan/admin/scripts/promote \
 D-lib-channels                \
 D-lib-commands                \
 D-lib-midi                    \
 D-deuce                       \
 D-duim                        \
 D-environment                 \
 D-runtime-manager             \
 D-databases                   \
 D-gnu                         \
 D-examples                    \
 D-macos                       \
 D-partners                    \
 D-patches                     \
 D-qa                          \
 D-tools-editor-templates      \
 D-tools-map-statistics        \
 D-tools-templates
