module = GObject-2
module-deps = GLib-2
headers-dir = ../headers/glib-2.0/gobject
headers = \
	gboxed.h \
	gclosure.h \
	genums.h \
	gmarshal.h \
	gobject.h \
	gparam.h \
	gparamspecs.h \
	gsignal.h \
	gsourceclosure.h \
	gtype.h \
	gtypemodule.h \
	gtypeplugin.h \
	gvaluearray.h \
	gvalue.h \
	gvaluetypes.h

include ../early.mk
include module.mk
include ../late.mk
