Origin:     OMG-IDL
IDL-file:   ../ir.idl
Include: ..
Prefix: ir
Protocol:      no
Stubs:	yes
Skeletons: no
Libraries: common-dylan,corba-protocol,orb-core
Modules: common-dylan,corba-protocol,orb-core
