Origin:     OMG-IDL
IDL-file:   ..\ir.idl
Include: ..
Prefix: ir
Protocol:      no
Stubs:	yes
Skeletons: no
Libraries: functional-dylan,corba-protocol,orb-core
Modules: functional-dylan,corba-protocol,orb-core
