#!/usr/local/bin/bash
#     Script: lw-license-variables
#     Author: Shri Amit(amit)
#      Usage: source lw-license-variables
#   Synopsis: The following script sets up the license server variables
#             for lispworks images for the various sites
#######################################################################

site=`domainname | cut -f1 -d "."`
## Lispworks licensing variables to enable images to run  ##
## Note that currently 1cc, menlo and hall have licensing ##
## and hence these variables must be set to "only"        ##
##
LISPWORKS_CHECK_NETWORK=only
LW_CHECK_NETWORK=only

## For sites that dont have license servers - reset variables ##
## These sites must have keyfiles installed for each machine  ##
## that lispworks needs to be run on. Send mail to lispworks- ##
## support to obtain keyfiles.                                ##
##
case $site in
	ed) LISPWORKS_CHECK_NETWORK=no
            LW_CHECK_NETWORK=no ;;
   seattle) LISPWORKS_CHECK_NETWORK=no
            LW_CHECK_NETWORK=no ;;
      utah) LISPWORKS_CHECK_NETWORK=no
            LW_CHECK_NETWORK=no ;;
esac 
export LISPWORKS_CHECK_NETWORK
export LW_CHECK_NETWORK

#eof