
**C3 superclass linearization**
*2012-01-25*

We implemented the C3 superclass linearization algorithm and
enabled it by default. This is more intuitive and will allow for
further performance improvements.

:doc:`Read more... </news/2012/01/21/c3>`

**Dswank - emacs and DIME**
*2011-12-12*

We developed DIME, the Dylan interaction mode for emacs, based
on SLIME. Now, you can browse the class hierarchy, get
argument lists, locate definitions, compile, view warnings and
more, all from within emacs!

:doc:`Read more... </news/2011/12/12/dswank>`

**New release: 2011.1**
*2011-12-10*

We just released Open Dylan 2011.1. This release is our first
since moving to GitHub and relicensing under a more liberal
license. It brings many bugfixes, inmproved platform support
and new features.

:doc:`Read more... </news/2011/12/10/new_release>`

**New Documentation**
*2011-11-22*

We're revitalizing our documentation and moving to a new
publishing system. We'll soon be able to provide our
documentation in PDF and ePub as well as HTML, with it
looking much better and being more maintainable than
in the past.

:doc:`Read more... </news/2011/11/22/new_documentation>`

**Welcome to the New Website!**
*2011-11-22*

As part of recharging Open Dylan development, we've re-done the
website and cleaned up a lot of the old, out-dated material here.

If you're looking for some of the old material, it can be found
over at `<http://old.opendylan.org/>`_.

