:doc:`Dylan Hack-a-thon: July 13-14, 2013 </news/2013/06/30/dylan-hack-a-thon>` *- 2013-06-30*
  No matter if you know Dylan or not, we can help you
  `learn Dylan <http://opendylan.org/books/dpg/>`_ or put your
  other skills to use. We've got a good `list of tasks
  <https://github.com/dylan-lang/opendylan/wiki>`_ that we're
  collecting and some people will bring their own Dylan-related
  projects.

:doc:`Updated Dylan Programming Guide </news/2013/01/21/dylan-programming-guide>` *— 2013-01-21*
  The Dylan Programming Guide has been updated to our
  new documentation format and is now available in
  PDF and ePub formats.

:doc:`New release: 2012.1 </news/2012/12/20/new-release>` *— 2012-12-20*
  We just released Open Dylan 2012.1. This release brings many
  bugfixes, improved platform support and new features.
