:doc:`Updated Dylan Programming Guide </news/2013/01/21/dylan-programming-guide>` *— 2013-01-21*
  The Dylan Programming Guide has been updated to our
  new documentation format and is now available in
  PDF and ePub formats.

:doc:`New release: 2012.1 </news/2012/12/20/new-release>` *— 2012-12-20*
  We just released Open Dylan 2012.1. This release brings many
  bugfixes, improved platform support and new features.

:doc:`Improved editor support </news/2012/10/18/editor-support>` *— 2012-10-18*
  Bugs in the syntax highlighting support for Textmate
  and Sublime Text as well as for vim have been fixed.
