module = GDK-2
module-deps = GLib-2 GObject-2 Pango GDK-Pixbuf-2
headers-dir = ../headers/gtk-2.0/gdk
headers = \
	gdkcolor.h \
	gdkcursor.h \
	gdkdisplay.h \
	gdkdisplaymanager.h \
	gdkdnd.h \
	gdkdrawable.h \
	gdkevents.h \
	gdkfont.h \
	gdkgc.h \
	gdk.h \
	gdkimage.h \
	gdkinput.h \
	gdkkeys.h \
	gdkkeysyms.h \
	gdkpango.h \
	gdkpixbuf.h \
	gdkpixmap.h \
	gdkproperty.h \
	gdkregion.h \
	gdkrgb.h \
	gdkscreen.h \
	gdkselection.h \
	gdktypes.h \
	gdkvisual.h \
	gdkwindow.h

include ../early.mk
include module.mk
include ../late.mk
