#!/usr/local/bin/bash
#      Script: build-clim
#      Author: Shri Amit(amit)
usage=" Usage: $0 -i <Image> -t <Target> -m <Usernames> 
	       -l <LogFile> -e"
# Opts & Flgs: -i: Source image, default: lw+dylan-$platform
#              -t: Target image, default: lw+dylan+clim-$platform.$suffix
#              -l: Logfile, default: build-clim-log-$host-$platform.$suffix
#              -m: Sends mail upon completion. (eg: -m foo,bar,foobar)
#              -e: Flag, sends mail to usernames ONLY if an error occurs"
#    Synopsis: . Loads the clim libraries into <Image>, save to <Target>. 
#              . If -m option has arg(s), sends mail upon completion.
#              . If -e flag is enabled, sends mail only upon error
#              . Restores link in $localdir,deletes old images,logs
#######################################################################
## Application exit status legend ##
##  0: Build successful
##  1: Invalid command line argument
##  2: The build exited abnormally from within lispworks

source /u/dylan/admin/builds/env.bash
targetdir=/u/swm/dylan/local

## Parse the options & flags on the command line ##
while getopts i:t:m:l:e option
do case $option in
     i) image=$OPTARG;;
     t) target=$OPTARG;;
     m) usernames=$OPTARG;;
     l) logfile=$OPTARG;;
     e) error_only=Yes;;
    \?) echo $usage
        exit 1;;
   esac
done
shift `expr $OPTIND - 1`

## Assign defaults to options & flags ##
image=${image:-$localdir/lw+dylan-$platform}
target=${target:-$localdir/lw+dylan+clim-$platform.$suffix}
logfile=${logfile:-$logsdir/build-clim-log-$host-$platform.$suffix}
usernames=${usernames:-unspecified}
error_only=${error_only:-No}

## Everything from here goes to the logfile ##
## Prompt the options                       ##
##
{
    echo "Starting at: `date`"
    echo "Running $0 with options:"
    echo "     The source image is: $image"
    echo "     The target image is: $target"
    echo "            Send mail to: $usernames"
    echo "Send mail on error only?: $error_only"
    echo "          The logfile is: $logfile"
    echo

## Build the image ##
##
$image -init - <<SCRIPT
(with-build-handler
  (format t "~&Loading clim.~%")
  (load "~lsupport/standard-installation/clim/load-clim-into-lw-3-2-2.lisp")
  (format t "~&Loading clim env and clim dylan env.~%")
  (load "$admindir/load-clim-env")
  (format t "~&Saving clim image as ~a~%" "$target")
  (user::save-emulator-image "$target")
  (bye))
SCRIPT
    status=$?
    echo "Ending at: `date`"
    subject="Report for clim build on $host-$platform"
    if ! [ -f $target -a $status = 0 ]; then
	message="The clim build exited with an exit status $status"
	case $usernames in
	   unspecified) echo $message;;
	   *) send-mail "$message" "$usernames" "$logfile" "$subject" ;;
	esac
	exit 2;
    else
	message="The clim build completed successfully."
	if [ "$usernames" != "unspecified" -a "$error_only" = "No" ]; then
	    send-mail "$message" "$usernames" "$logfile" "$subject"
	else
	    echo $message
	fi
	if test -f $target; then
	    $admindir/remove-old-files $localdir/lw+dylan+clim-$platform 1
	    rm -f $targetdir/lw+dylan+clim-$platform
	    ln -s $target $targetdir/lw+dylan+clim-$platform
	    rm -f $localdir/lw+dylan+clim-$platform
	    ln -s $target $localdir/lw+dylan+clim-$platform
	    $admindir/remove-old-files $logsdir/build-clim-log-$host-$platform $logstokeep
	fi
    fi

} &> $logfile

exit 0
#eof
