#! /usr/local/bin/bash
#      Script: distribute-candidate
#      Author: Doug Dodds
usage=" Usage: $0 <release-name> <candidate-name> <Site1> <Site2> .. .."
# Opts & Args:  <release-name>: the directory designator for the
#               current version, e.t., 1.1/candidate7 => 1.1
#               <candidate-name>: the name of the candidate
#               <Site>: Domain names of valid developer sites.
#               Currently the recognized sites are:
#               1cc, cam, long, ed
#
#    Synopsis: Executes ls -l at all <Site>s specified
#              Note that if nothing is specified then the cmd is
#              executed at all sites.
#############################################################
## Application exit status legend ##
## 0: Successful
## 1: Candidate number not specified
## 2: Unrecognized site

## Parse the command line and decide the sites and machines ##
##
release_name="$1"
case $release_name in
    "") echo "A release name must be specified"
        echo $usage
        exit 1 ;;
    *) ;;
esac
shift

candidate_name="$1"
case $candidate_name in
    "") echo "A candidate name must be specified"
        echo $usage
	exit 1 ;;
     *) ;;
esac
shift

sites=$@
case $sites in
   "") sites="1cc long ed" ;;
    *) ;;
esac
for i in $sites; do 
    case $i in
	1cc) machine="$machine banshee.functionalobjects.com" ;;
	long) machine="$machine casper.long.harlequin.co.uk" ;;
	ed) machine="$machine lordosis.ed.harlequin.co.uk" ;;
	cam) machine="$machine ventral.cam.harlequin.co.uk" ;;
	*) echo "$0: Error - Site $i unrecognized"
           echo $usage
           exit 2 ;;

    esac
done

echo "Starting at: `date`"
 
for i in $machine; do
    echo
    echo " $i"
    rsh $i -n ls -l /u/dylan/releases/$release_name/$candidate_name
done

echo

#eof
