@echo off

:ENSURE_CVS_LOGS
if exist "%FUNCTIONAL_DEVELOPER_CVS_LOGS%" goto ensure_build_logs
mkdir %FUNCTIONAL_DEVELOPER_CVS_LOGS%

:ENSURE_BUILD_LOGS
if exist "%FUNCTIONAL_DEVELOPER_BUILD_LOGS%" goto ensure_build
mkdir %FUNCTIONAL_DEVELOPER_BUILD_LOGS%

:ENSURE_BUILD
if exist "%FUNCTIONAL_DEVELOPER_USER_BUILD%" goto ensure_bin
mkdir %FUNCTIONAL_DEVELOPER_USER_BUILD%

:ENSURE_BIN
if exist "%FUNCTIONAL_DEVELOPER_USER_INSTALL%"\bin goto ensure_lib
mkdir %FUNCTIONAL_DEVELOPER_USER_INSTALL%\bin

:ENSURE_LIB
if exist "%FUNCTIONAL_DEVELOPER_USER_INSTALL%"\lib goto end
mkdir %FUNCTIONAL_DEVELOPER_USER_INSTALL%\lib
goto end

:END
