#!/usr/local/bin/perl
#   Script:  get-host-name
#   Author:  princew
# Synopsis:  Acquiring the hostname from this script ensures
#            that only the name of the host and not its domain
#            is returned, which is usually the case when
#            `hostname` is executed in a remote shell
#            e.g: rsh banshee hostname
#                 loading .bashrc
#                 banshee.functionalobjects.com
#
#                 rsh banshee /u/dylan/admin/builds/get-host-name
#                 loading .bashrc
#                 banshee
# Revision: By: amit On: Dec 05 1996 Rea: Add this header and remove
#           .pl extension from the name of executable script
#           By: amit On: Dec 30 1996 Rea: use uname -n instead of
#           hostname because uname is more universal.
#           By: amit On: Dec 31 1996 Rea: make it look in both ucb
#           and in bin
####################################################################

$PATH="/usr/bin:/usr/ucb:$PATH";
$machine_name=`uname -n`;

$machine_name =~ s/\W.*//;
$machine_name =~ s/\W.*//;

print "$machine_name\n";

#eof
