#!/usr/bin/sh

# Generate an Emacs "TAGS" file for Dylan source files
#
# Usage:
#	dtags *.dylan
#
# Then you can use the Emacs `Meta-.' command to find definitions of Dylan
# identifiers in those files.

# Documentation for the "gema" utility can be found at URL:
#	http://webhost.harlequin.com/~gray/gema-intro.html
# (internally) or (externally):
#	ftp://ftp.harlequin.com/pub/gema/www/top.html

# $Header: /scm/cvs/fundev/tools/gnuemacs/dtags,v 1.1 2004/03/12 00:42:10 cgay Exp $

outfile=TAGS
case $1 in
  -o) outfile=$2; shift; shift;;
  -*) echo 'unrecognized option:' $1; shift;;
esac

/u/gray/bin/gema -f /u/dylan/tools/gnuemacs/tags.pat -out $outfile $*
