#
# Build HTML documentation on Pull Request
#

name: Build documentation

on:
  pull_request:
    paths:
      - 'documentation/**/*.rst'
      - 'documentation/**/conf.py'

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-documentation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      #
      # Build documentation installing first 'furo' theme dependencies
      #

      - uses: ammaraskar/sphinx-action@master
        with:
          pre-build-command: "echo furo >> documentation/website/requirements.txt"
          docs-folder: "documentation/website"

