name: Build Release

on:
  # Manual trigger only
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest,ubuntu-latest]
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      # Install a bootstrap compiler.
      - uses: dylan-lang/install-opendylan@v3

      - name: Install Dependencies
        run: |
          case "$RUNNER_OS" in
            macOS)
              brew install autoconf automake ninja ;;
            Linux)
              sudo apt install -y lld ;;
          esac

      - name: "Build with batteries"
        run: ./build/unix/release-with-batteries.sh

      - uses: actions/upload-artifact@v4
        with:
          name: opendylan-release-tarball
          # The - in the path is to omit the opendylan.tar.bz2 symlink.
          path: release/opendylan-*.tar.bz2
          compression-level: 0
          retention-days: 3
          overwrite: true
          if-no-files-found: error
