#
# Build HTML documentation on Pull Request
#

name: Build documentation

on:
  pull_request:
    paths:
      - 'documentation/**/*.rst'
      - 'documentation/**/conf.py'

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-documentation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "documentation/building-with-duim"

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "documentation/corba-guide"

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "documentation/duim-reference"

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "documentation/getting-started-ide"

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "documentation/hacker-guide"

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "documentation/intro-dylan"

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "documentation/library-reference"

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "documentation/man-pages"

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "documentation/project-notebook"

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "documentation/release-notes"

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "documentation/style-guide"

